name: ci
run-name: ci
on:
  push:
    branches:
      - main
jobs:
  build-container-image:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: pverbist
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Run build
        run: earthly --ci --push +build \
             --secret password="$REGISTRY_PASSWORD"
        env:
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
