name: ci
run-name: ci
on:
  push:
    branches:
      - main
jobs:
  build-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buidlx
        uses: docker/setup-buildx-action@v3
      - name: Login to c8n.io
        uses: docker/login-action@v3
        with:
          registry: c8n.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: c8n.io/pverbist/whoami:latest
